p8105_hw1_ECW2178
================
2025-09-21

# Problem 1

## Load Libraries and Datasets

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.4     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(moderndive)
data("early_january_weather")
```

## Exploratory Data Analysis and Scatterplot

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
mean(early_january_weather$temp)
```

    ## [1] 39.58212

``` r
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point()
```

![](p8105_hw1_ECW2178_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
ggsave("early_january_weather_scatterplot.pdf", height = 4, width = 6)
```

There are 15 variables in this dataset: origin, year, month, day, hour,
temperature, dew point, humidity, wind direction, wind speed, wind gust,
precipitation, pressure, visibility, and time in hours.

Meaningful variables include time in hours, temperature, and humidity.

There are 358 rows and 15 columns in this early_january_weather dataset.
The mean temperature is 39.58212 Fahrenheit.

While there is is considerable variabiliy in temperature and humidity,
the average temperature increases as the days pass in January.
Furthermore, the average humidity increases as the days pass in January.

# Problem 2

## Create Dataset and Caluclate Variable Means

``` r
hw_df = tibble(
  samp = rnorm(10),
  greater_zero = samp > 0, 
  vec_char = c("Hello", "My", "name", "is", "Edmund", "Wong", "I", "am", "studying", "Biostatistics"),
  vec_factor = factor(c("Low", "Medium", "High", "Low", "Medium", "High", "Low", "Medium", "High", "Low"))
)

mean(pull(hw_df, samp))
```

    ## [1] -0.3506534

``` r
mean(pull(hw_df, greater_zero))
```

    ## [1] 0.2

``` r
mean(pull(hw_df, vec_char))
```

    ## Warning in mean.default(pull(hw_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(hw_df, vec_factor))
```

    ## Warning in mean.default(pull(hw_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

The only variables that were able to compute the mean were the rnom
sampling variable and the greater than zero variable because these are
numeric variables. It doesn’t make sense to take the mean of a character
or a factor variable.

## Convert Variables to Numeric

``` r
new_hw_df = tibble(
  samp = rnorm(10),
  greater_zero = as.numeric(hw_df$greater_zero),
  vec_char = as.numeric(hw_df$vec_char),
  vec_factor = as.numeric(hw_df$vec_factor)
)
```

When you try and force the logical, character, and factor variables,
NA’s are force into the character vectors and the logical and factor
variables are changed to numbers instead of their original values. This
helps explain the errors in taking the means of the original values of
these variables because character vectors have no way of being numerical
while the logical and factor variables have to change their values to
make sense as a numerical value.
